services:
  app:
    build: .
    image: songs-app
    container_name: songs-app
    restart: always
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      data:
        condition: service_healthy
    env_file:
      - .env

  data:
    image: postgres:15
    container_name: postgres-db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build: ./frontend
    image: songs-frontend
    container_name: songs-frontend
    ports:
      - "8088:80"
    depends_on:
      - app